version: "3.9"

services:
  tuwayki_food:
    image: tuwayki_food:latest
    container_name: tuwayki_food
    restart: unless-stopped
    ports:
      - "3003:3003"
    env_file:
      - .env
    environment:
      - ENV=prod
    volumes:
      - food_web:/app/.web
    networks:
      - tuwayki_net

volumes:
  food_web:

networks:
  tuwayki_net:
    external: true
