"""Pagina admin de carta — gestión de categorias y productos."""

from __future__ import annotations

import reflex as rx

from app.components.shared import app_shell
from app.states.food_state import CategoriaView, FoodState, ProductoView


def _categoria_row(cat: CategoriaView) -> rx.Component:
    return rx.hstack(
        rx.vstack(
            rx.hstack(
                rx.text(cat.nombre, font_size="14px", font_weight="600", color="#0F172A"),
                rx.cond(
                    cat.activa,
                    rx.badge("Activa", background="#DCFCE7", color="#15803D", border_radius="5px", font_size="10px"),
                    rx.badge("Inactiva", background="#FEE2E2", color="#B91C1C", border_radius="5px", font_size="10px"),
                ),
                spacing="2",
                align="center",
            ),
            rx.cond(
                cat.descripcion != "",
                rx.text(cat.descripcion, font_size="11px", color="#94A3B8"),
                rx.fragment(),
            ),
            spacing="0",
            align="start",
        ),
        rx.spacer(),
        rx.text(f"Orden: {cat.orden}", font_size="11px", color="#94A3B8"),
        rx.button(
            "Editar",
            on_click=FoodState.editar_categoria(cat.id),
            background="#FFF7ED",
            color="#EA580C",
            border="1px solid #FED7AA",
            border_radius="6px",
            font_size="11px",
            cursor="pointer",
            padding_x="8px",
            padding_y="4px",
            _hover={"opacity": "0.85"},
        ),
        rx.button(
            rx.cond(cat.activa, "Desactivar", "Activar"),
            on_click=FoodState.toggle_categoria_activa(cat.id),
            background=rx.cond(cat.activa, "#FEF2F2", "#F0FDF4"),
            color=rx.cond(cat.activa, "#B91C1C", "#15803D"),
            border=rx.cond(cat.activa, "1px solid #FECACA", "1px solid #BBF7D0"),
            border_radius="6px",
            font_size="11px",
            cursor="pointer",
            padding_x="8px",
            padding_y="4px",
            _hover={"opacity": "0.85"},
        ),
        width="100%",
        align="center",
        padding="10px 14px",
        background="#FFFFFF",
        border_radius="8px",
        border="1px solid #E2E8F0",
    )


def _categoria_form() -> rx.Component:
    return rx.vstack(
        rx.text(
            rx.cond(FoodState.categoria_form_id > 0, "Editar Categoria", "Nueva Categoria"),
            font_size="14px",
            font_weight="700",
            color="#EA580C",
        ),
        rx.input(
            placeholder="Nombre *",
            value=FoodState.categoria_form_nombre,
            on_change=FoodState.set_categoria_form_nombre,
            background="#FFFFFF",
            border="1px solid #E2E8F0",
            color="#0F172A",
            border_radius="8px",
            padding_x="12px",
            padding_y="8px",
            font_size="13px",
            width="100%",
        ),
        rx.input(
            placeholder="Descripcion (opcional)",
            value=FoodState.categoria_form_descripcion,
            on_change=FoodState.set_categoria_form_descripcion,
            background="#FFFFFF",
            border="1px solid #E2E8F0",
            color="#0F172A",
            border_radius="8px",
            padding_x="12px",
            padding_y="8px",
            font_size="13px",
            width="100%",
        ),
        rx.input(
            placeholder="Orden",
            value=FoodState.categoria_form_orden,
            on_change=FoodState.set_categoria_form_orden,
            background="#FFFFFF",
            border="1px solid #E2E8F0",
            color="#0F172A",
            border_radius="8px",
            padding_x="12px",
            padding_y="8px",
            font_size="13px",
            width="80px",
            type="number",
        ),
        rx.hstack(
            rx.button(
                "Cancelar",
                on_click=FoodState.cancelar_categoria_form,
                background="#F1F5F9",
                color="#64748B",
                border="1px solid #E2E8F0",
                border_radius="8px",
                font_size="13px",
                cursor="pointer",
                _hover={"opacity": "0.85"},
            ),
            rx.button(
                "Guardar Categoria",
                on_click=FoodState.guardar_categoria,
                background="#EA580C",
                color="#FFFFFF",
                border_radius="8px",
                font_size="13px",
                font_weight="700",
                cursor="pointer",
                flex="1",
                _hover={"background": "#C2410C"},
            ),
            spacing="2",
            width="100%",
        ),
        spacing="3",
        padding="16px",
        background="#FFF7ED",
        border="1px solid #FED7AA",
        border_radius="12px",
        width="100%",
    )


def _producto_row(prod: ProductoView) -> rx.Component:
    return rx.hstack(
        rx.cond(
            prod.imagen_url != "",
            rx.image(
                src=prod.imagen_url,
                width="40px",
                height="40px",
                object_fit="cover",
                border_radius="6px",
                border="1px solid #E2E8F0",
                flex_shrink="0",
            ),
            rx.box(
                rx.icon(tag="utensils", size=16, color="#CBD5E1"),
                width="40px",
                height="40px",
                border_radius="6px",
                background="#F8FAFC",
                border="1px solid #E2E8F0",
                display="flex",
                align_items="center",
                justify_content="center",
                flex_shrink="0",
            ),
        ),
        rx.vstack(
            rx.hstack(
                rx.text(prod.nombre, font_size="13px", font_weight="600", color="#0F172A"),
                rx.cond(
                    prod.disponible,
                    rx.badge("Disponible", background="#DCFCE7", color="#15803D", border_radius="5px", font_size="10px"),
                    rx.badge("No disponible", background="#FEE2E2", color="#B91C1C", border_radius="5px", font_size="10px"),
                ),
                spacing="2",
                align="center",
                flex_wrap="wrap",
            ),
            rx.hstack(
                rx.text(prod.precio_texto, font_size="13px", font_weight="700", color="#EA580C"),
                rx.text("·", color="#CBD5E1", font_size="10px"),
                rx.text(prod.categoria_nombre, font_size="11px", color="#94A3B8"),
                spacing="1",
                align="center",
            ),
            spacing="0",
            align="start",
            flex="1",
            min_width="0",
        ),
        rx.spacer(),
        rx.button(
            "Editar",
            on_click=FoodState.editar_producto(prod.id),
            background="#FFF7ED",
            color="#EA580C",
            border="1px solid #FED7AA",
            border_radius="6px",
            font_size="11px",
            cursor="pointer",
            padding_x="8px",
            padding_y="4px",
            _hover={"opacity": "0.85"},
        ),
        rx.button(
            rx.hstack(
                rx.cond(
                    prod.disponible,
                    rx.icon(tag="toggle_right", size=14),
                    rx.icon(tag="toggle_left", size=14),
                ),
                rx.text(rx.cond(prod.disponible, "Deshabilitar", "Activar"), font_size="11px"),
                spacing="1", align="center",
            ),
            on_click=FoodState.toggle_producto_disponible(prod.id),
            background=rx.cond(prod.disponible, "#FEF2F2", "#F0FDF4"),
            color=rx.cond(prod.disponible, "#B91C1C", "#15803D"),
            border=rx.cond(prod.disponible, "1px solid #FECACA", "1px solid #BBF7D0"),
            border_radius="6px",
            font_size="11px",
            cursor="pointer",
            padding_x="8px",
            padding_y="4px",
            _hover={"opacity": "0.85"},
        ),
        width="100%",
        align="center",
        padding="10px 14px",
        background="#FFFFFF",
        border_radius="8px",
        border="1px solid #E2E8F0",
        gap="10px",
    )


def _producto_form() -> rx.Component:
    return rx.vstack(
        rx.text(
            rx.cond(FoodState.producto_form_id > 0, "Editar Producto", "Nuevo Producto"),
            font_size="14px",
            font_weight="700",
            color="#EA580C",
        ),
        rx.hstack(
            rx.input(
                placeholder="Nombre del producto *",
                value=FoodState.producto_form_nombre,
                on_change=FoodState.set_producto_form_nombre,
                background="#FFFFFF",
                border="1px solid #E2E8F0",
                color="#0F172A",
                border_radius="8px",
                padding_x="12px",
                padding_y="8px",
                font_size="13px",
                flex="1",
            ),
            rx.input(
                placeholder="Precio *",
                value=FoodState.producto_form_precio,
                on_change=FoodState.set_producto_form_precio,
                background="#FFFFFF",
                border="1px solid #E2E8F0",
                color="#0F172A",
                border_radius="8px",
                padding_x="12px",
                padding_y="8px",
                font_size="13px",
                width="100px",
                type="number",
                min="0.01",
                step="0.01",
            ),
            spacing="2",
            width="100%",
        ),
        rx.select(
            FoodState.categorias_activas_nombres,
            value=FoodState.producto_form_categoria_nombre,
            on_change=FoodState.set_producto_form_categoria,
            background="#FFFFFF",
            color="#0F172A",
            border="1px solid #E2E8F0",
            border_radius="8px",
            padding_x="12px",
            padding_y="8px",
            font_size="13px",
            width="100%",
        ),
        # ── Imagen del plato ──────────────────────────────────────────
        rx.vstack(
            rx.text("Imagen del plato", font_size="12px", font_weight="600", color="#64748B"),
            rx.cond(
                FoodState.producto_form_imagen_url != "",
                rx.hstack(
                    rx.image(
                        src=FoodState.producto_form_imagen_url,
                        width="80px",
                        height="80px",
                        object_fit="cover",
                        border_radius="8px",
                        border="1px solid #E2E8F0",
                    ),
                    rx.vstack(
                        rx.text("Imagen cargada", font_size="11px", color="#15803D", font_weight="600"),
                        rx.button(
                            "Quitar imagen",
                            on_click=FoodState.quitar_imagen_producto,
                            background="#FEF2F2",
                            color="#B91C1C",
                            border="1px solid #FECACA",
                            border_radius="6px",
                            font_size="11px",
                            cursor="pointer",
                            padding_x="8px",
                            padding_y="3px",
                            _hover={"opacity": "0.85"},
                        ),
                        spacing="2",
                        align="start",
                    ),
                    spacing="3",
                    align="center",
                ),
                rx.upload(
                    rx.vstack(
                        rx.icon(tag="image_plus", size=20, color="#94A3B8"),
                        rx.text("Arrastra o haz click", font_size="11px", color="#64748B"),
                        rx.text("JPG, PNG, WEBP — max 5MB", font_size="10px", color="#94A3B8"),
                        spacing="1",
                        align="center",
                    ),
                    id="upload_imagen_producto",
                    on_drop=FoodState.handle_upload_imagen_producto(
                        rx.upload_files(upload_id="upload_imagen_producto")
                    ),
                    accept={"image/jpeg": [".jpg", ".jpeg"], "image/png": [".png"], "image/webp": [".webp"]},
                    max_files=1,
                    border="2px dashed #E2E8F0",
                    border_radius="8px",
                    padding="16px",
                    width="100%",
                    background="#FAFAFA",
                    cursor="pointer",
                    _hover={"border_color": "#EA580C", "background": "#FFF7ED"},
                ),
            ),
            spacing="2",
            width="100%",
        ),
        rx.hstack(
            rx.button(
                rx.cond(FoodState.producto_form_disponible, "Disponible", "No disponible"),
                on_click=FoodState.set_producto_form_disponible(~FoodState.producto_form_disponible),
                background=rx.cond(FoodState.producto_form_disponible, "#DCFCE7", "#FEE2E2"),
                color=rx.cond(FoodState.producto_form_disponible, "#15803D", "#B91C1C"),
                border=rx.cond(FoodState.producto_form_disponible, "1px solid #BBF7D0", "1px solid #FECACA"),
                border_radius="6px",
                font_size="12px",
                cursor="pointer",
                _hover={"opacity": "0.85"},
            ),
            rx.spacer(),
            rx.button(
                "Cancelar",
                on_click=FoodState.cancelar_producto_form,
                background="#F1F5F9",
                color="#64748B",
                border="1px solid #E2E8F0",
                border_radius="8px",
                font_size="13px",
                cursor="pointer",
                _hover={"opacity": "0.85"},
            ),
            rx.button(
                "Guardar Producto",
                on_click=FoodState.guardar_producto,
                background="#EA580C",
                color="#FFFFFF",
                border_radius="8px",
                font_size="13px",
                font_weight="700",
                cursor="pointer",
                _hover={"background": "#C2410C"},
            ),
            spacing="2",
            width="100%",
        ),
        spacing="3",
        padding="16px",
        background="#FFF7ED",
        border="1px solid #FED7AA",
        border_radius="12px",
        width="100%",
    )


def _carta_content() -> rx.Component:
    return rx.vstack(
        rx.text("Carta / Admin", font_size="22px", font_weight="800", color="#0F172A"),
        rx.cond(
            FoodState.mensaje != "",
            rx.box(
                rx.text(FoodState.mensaje, font_size="12px", color="#334155"),
                background="#F1F5F9",
                border="1px solid #E2E8F0",
                border_radius="6px",
                padding="8px 12px",
                width="100%",
            ),
            rx.fragment(),
        ),
        rx.flex(
            # ─── Categorias ───────────────────────────────────────────────
            rx.vstack(
                rx.text("Categorias", font_size="15px", font_weight="700", color="#64748B"),
                _categoria_form(),
                rx.vstack(
                    rx.foreach(FoodState.categorias, _categoria_row),
                    spacing="2",
                    width="100%",
                ),
                spacing="3",
                flex="1",
                min_width="0",
                class_name="twk-panel",
            ),
            rx.divider(orientation="vertical", border_color="#E2E8F0", height="auto",
                       class_name="twk-sep"),
            # ─── Productos ────────────────────────────────────────────────
            rx.vstack(
                rx.text("Productos", font_size="15px", font_weight="700", color="#64748B"),
                _producto_form(),
                rx.vstack(
                    rx.foreach(FoodState.productos, _producto_row),
                    spacing="2",
                    width="100%",
                ),
                spacing="3",
                flex="1",
                min_width="0",
                class_name="twk-panel",
            ),
            gap="5",
            width="100%",
            align="start",
            class_name="twk-cols-lg",
        ),
        spacing="5",
        width="100%",
    )


@rx.page(route="/carta", on_load=FoodState.on_load_carta, title="TUWAYKIFOOD | Carta")
def carta_page() -> rx.Component:
    return app_shell(_carta_content(), page_key="carta")
